import { randomBytes, createHash } from 'node:crypto'

// Refresh tokens are long, random, opaque strings (NOT JWTs). Unlike a
// password, this value is generated by us and never typed by a human, so
// it's already high-entropy — a fast hash (SHA-256) is appropriate here,
// unlike the slow/memory-hard argon2 hash we use for passwords.

export const REFRESH_TOKEN_LIFETIME_SECONDS = 60 * 60 * 24 * 7 // 7 days

export function generateRawRefreshToken(): string {
  // 32 random bytes = 256 bits of entropy, hex-encoded for easy transport.
  return randomBytes(32).toString('hex')
}

export function hashRefreshToken(rawToken: string): string {
  return createHash('sha256').update(rawToken).digest('hex')
}

export function refreshTokenExpiry(): Date {
  return new Date(Date.now() + REFRESH_TOKEN_LIFETIME_SECONDS * 1000)
}
